### ISSUE TITLE
Error: androidResource

### ISSUE THREAD

**Issue by proczak1** [builttoroam/device_calendar#401]
Hello. Upgrade to 4.1.0 does work in debug, but not in release. I got error:

* What went wrong:
Execution failed for task ':device_calendar:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\Users\procz\.gradle\caches\transforms-3\cb82ab87932d631ec279de51e0d3f5d6\transformed\core-1.7.0\res\values\values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

**Comment by thomassth** [comment]
Ah I understand the problem now
#399 should fix this.

**Comment by proczak1** [comment]
Hey. Thanks for quick response. Yet i still dont get that how to solve that issue? Flutter run --release still stops :(

**Comment by thomassth** [comment]
Are you using the latest dev branch? We haven’t do a prerelease yet

Or build an app bundle, which somehow is not affected.

**Comment by proczak1** [comment]
Alright. It wirks when from github (develop)! Amazing :)
